### ISSUE TITLE
bcm2837: inbound ethernet is 11 Mbit/s against 100 Mbit/s outbound

### ISSUE THREAD

**Issue by pdfinn** [infernode-os/infernode#610]
## Measured

Pi 3B+, bare metal, LAN78xx over USB 2.0, 2MB per run, three runs each, timed end to end (outbound to the last byte received here; inbound to the board's FIN after its reader finishes). Inbound needs the peer's MSS capped to dodge #608 until that fix is on a board.

| direction | sink/source on the board | rate |
|---|---|---|
| outbound | MemFS -> TCP | **12.4 MB/s (100 Mbit/s)** |
| inbound | TCP -> /dev/null | **1.36 MB/s (11.1 Mbit/s)** |
| inbound | TCP -> MemFS file | 1.01 MB/s (8.3 Mbit/s) |

Outbound is within reach of what USB 2.0 gives in practice and needs nothing. Inbound is **9x slower**, and `/dev/null` as the sink rules out the filesystem: that figure is the network path alone.

## Why this is probably the receive path and not TCP

`os/init/etherusb.b`'s own comments describe the mechanism and the history:

- a bulk IN that finds nothing costs one NAKed transaction, so the reader polls; it used to sleep 20ms every time, and that sleep *was* the receive latency of the machine -- "a round trip on a wire measured in microseconds cost 44ms, and a TCP window of a few kilobytes divided by that is the 23KB/s this port was getting".
- the current loop polls at 1ms while there is reason to and backs off to 20ms when quiet (`rxpollms`, `rxactive`).
- the kernel data path (`os/port/devether.c`, bound at boot as "kernel data path ... burst 16384") reads one aggregation cap per transfer and walks the records.

So inbound is a poll-driven pipeline where outbound is not, which is the shape of a 9x gap. What is not yet known is where the time actually goes: the driver already keeps `nrd`, `rdbytes`, `rdmax`, `gapns`, `nempty`, `nempty0` and `emptymax` for exactly this question, and reading them across a measured inbound transfer would say whether the cost is empty polls, scheduling gaps, or per-transfer overhead.

## Worth measuring before optimising

1. Those counters, before and after a 2MB inbound run -- `rdmax` in particular says whether transfers are arriving aggregated (near 16KB) or one frame at a time.
2. Whether `#608`'s fix changes it. Full-size frames mean ~3% fewer frames for the same bytes, so the effect should be small; if it is large, something else is size-dependent.
3. Whether the "packed data file" path (`os/port/devether.c` `etherreadpacked`) is in use on this board, since the README records it was worth half the 9P round trips on the receive path.

## Reproducing

```
# on the board
listen -A 'tcp!*!8700' {cat > /dev/null} &
```

From a peer, connect with `TCP_MAXSEG` set to 1400, send 2MB, shut down the write side, and time until EOF comes back.

**Comment by pdfinn** [comment]
## Correction: inbound is not 11 Mbit/s, it is 12-33 Mbit/s and erratic

Five runs, same 2MB payload, **identical configuration**, timed the same way:

```
run 1   0.69s   2985 KB/s   24.4 Mbit/s
run 2   1.36s   1505 KB/s   12.3 Mbit/s
run 3   1.12s   1832 KB/s   15.0 Mbit/s
run 4   0.52s   3963 KB/s   32.5 Mbit/s
run 5   0.91s   2256 KB/s   18.5 Mbit/s
```

A 2.6x spread with nothing changed between runs. The 11.1 Mbit/s in the report above was a single sample at the bottom of that range and should not have been quoted as a figure. The honest statement is: **inbound ranges 12-33 Mbit/s, median about 18**, against **100 Mbit/s outbound that repeats within 1%**.

The variance is itself the most useful datum. A poll-driven receive path contending with other processes for a single-threaded interpreter would look exactly like this: consistent when the machine is only transmitting, erratic when the receive side has to be scheduled to make progress. So whatever is measured next should report a distribution, not a mean -- the same lesson `os/init/etherusb.b` already records about its empty-read timings ("the shape of the distribution, not just its mean").

## And the tuning knob does not apply here

`etherusb.b` exposes `rxpoll <ms> <count>` on a conversation ctl, documented as a file specifically so the poll interval can be tuned without rebuilding the kernel. On this board it is unreachable:

```
{echo 'rxpoll 1 5000' >[1=0]} <> /net/ether0/clone
  -> echo: write error: bad process or channel control request
```

Because the **kernel** data path is bound (`ether0: kernel data path bound (lan78xx, 1000 mbps, burst 16384)`), `os/port/devether.c` owns `/net/ether0`'s ctl and does not implement `rxpoll`, and the Limbo `rxproc` whose behaviour those knobs control is not in the path at all. The kernel reader has its own fixed `tsleep(..., 1)` on an empty read with nothing exposed to tune.

That is worth fixing on its own terms: the knob was added because measuring beat guessing, and the migration to the kernel data path silently took it away. Either `devether.c` should accept `rxpoll` and use it, or the file should stop advertising a control that the shipping configuration ignores.

**Comment by pdfinn** [comment]
## Localised: no read is posted for 87% of the time

`rxstats` on ether0's ctl prints the driver's own counters and resets them, so two writes bracket a workload. Around a 2MB inbound transfer (2.16s, 7.8 Mbit/s):

```
rx: 244 reads 2170 KB mean 9110 B max 16104; in-read 289162 us (mean 1185 us)
```

| | |
|---|---|
| bytes per read | **9110** (burst cap is 16384; max seen 16104) |
| reads | 244 in 2.16s = **113/s** |
| cycle per read | **8.85 ms** |
| time inside the read | **1.19 ms**, i.e. 13% |

So for roughly **7.7 ms of every 8.85 ms there is no bulk IN outstanding**, and the device has nowhere to put what it has. Throughput is just `bytes/read x reads/s` = 9110 x 113 = 1.03 MB/s = 8.2 Mbit/s, which is the measured figure. It scales directly with reads per second.

### Two hypotheses this kills

- **"The device is not aggregating."** It is: 9110 bytes mean, 16104 max. Whatever `Lburstcap` and the burst plumbing are doing, they are doing it.
- **"Frames arrive one per read, so throughput is pinned to the poll rate."** That was my guess in the report above, and the arithmetic happened to land in the measured range for the wrong reason.

### Why outbound does not have this problem

`ethertxproc` blocks in `qbread` until a frame exists and then `qget`s everything else that arrived while the previous transfer was in flight, so one scheduling event serves a whole batch. The receive side has no equivalent: the reader must be scheduled to issue *each* read, and an empty read costs a `tsleep(..., 1)`. Outbound pays scheduling per batch; inbound pays it per read, and then waits.

### What would move it

Keep a read always posted -- two or more outstanding bulk INs, or a double-buffered reader, so the device never has data with nobody asking. That is `os/port/devether.c`'s `ethereadproc` and needs a kernel rebuild, so it is not a config change.

Worth noting the measurement includes my own monitoring traffic over the network console on the same interface, which can only have made the gaps worse, not better. A quieter run would be a fairer baseline, and a serial-only console would be fairest.

### There is also a profiler already in the tree

`os/port/devether.c` serves a kernel PC histogram (`profbuck`, 64-byte text buckets, filled from the clock interrupt, reset on a read from offset 0, so two reads bracket a workload). Its comment says "the first question profiled was the network path". Mapping its hot offsets to symbols would say where the 7.7 ms actually goes rather than only that it is missing -- worth doing before changing the reader, and it needs no reflash.

**Comment by pdfinn** [comment]
## Receive poll backoff: tried, measured inert, dropped

Recording the numbers here because the change itself is not worth keeping in the tree.

**What was tried.** A backoff in `devether`'s reader (`os/port/devether.c`), reusing `os/init/etherusb.b`'s constants: poll every 1ms while there is reason to, `Rxactive` of those, then fall back to `Rxidle`.

**Why it does nothing.** `Rxactive` is 2000 fast polls, so backing off requires two seconds in which not one frame arrives. A live segment never provides that -- broadcast traffic resets the counter long before. Built, booted, measured on the board: idle unchanged at **1000 bulk IN/s and 2019 interrupts/s**, and `rxstats` reported **zero** backoffs. Throughput unchanged in both directions. The Limbo driver these constants came from presumably never backed off either, and nobody would have noticed, because the only symptom is idle cost.

**The measurements worth keeping**, all from the board:

| | |
|---|---|
| idle, no traffic | 1000 bulk IN/s, 2019 interrupts/s, 1021 sleep/wake cycles/s |
| inbound 2MB | 244 devether reads, 18607 channel ops -> **~76 ops per read** |
| outbound 2MB | 577 bulk OUTs carry the data, while receive ran 17747 bulk INs in 0.22s (**80000/s**), machine at 164000 interrupts/s |
| channel timeouts | +1 in 37s -- the 200ms `Chantmout` pathology is NOT occurring |
| interrupt path | `woken +38089` against `tmout +1`, so it works; usbdwc.c's comment that "this driver never takes a USB interrupt" is stale |

So the cost is inside `chanio`, not in the reader's sleep: roughly four channel operations per 512-byte USB packet, each with an interrupt and a sleep/wake.

**Correction to the framing in this issue.** I characterised outbound as consistent (100 Mbit/s +/-1%) and inbound as erratic, and built a structural story on it. A proper A/B against the original kernel, running image verified from `/dev/bootimage` at each step, says outbound swings on the original kernel too:

```
original kernel (2149765):  103.1, 46.8, 41.3 Mbit/s
current kernel  (2155477):   77.8, 47.1, 99.5  and  98.0, 43.0, 80.3
```

The 100 +/-1% was three lucky consecutive runs. **Both directions are erratic, and always were** -- which is a more useful description of this bug than the one above it.

**Where the fix actually lives**, per `os/init/etherusb.b`'s own note, which predates all of this: a bulk IN ending on an exact 512-byte multiple is invisible to the host's read layer, and "the real fix is zero-length-packet awareness in the DWC read path". That is the work, with ops-per-read (76 now, ~18 correct) and the record-desync count as the two metrics.

**Comment by pdfinn** [comment]
Kernel panic on the board, caught by the serial capture 2026-09-14 15:23:54 local, kernel image 2172829 (`fix/bt-first-light` tree, mailbox alignment included), while a 9P mount over the LAN78xx was copying a 59 KB file from the dev host:

```
*** unhandled exception ***
  vector:  sync from current EL, SP_ELx
  esr:     0x96000045  ec=0x25 (data abort, same EL)   iss 0x45: write, translation fault level 1
  far:     0x00000028657b34f0
  elr(pc): 0x0000000000080284
  x0:  0x00000028657b34f0   x8: 0x00000028657b2e18
  trace:  0xa9f28 etherrxproc+0x1b8   0x816c0 linkproc+0xec
kernel exit (called from 9f2c4, pid 37 ether0rx)
```

A write through a pointer whose top bits are garbage (`0x28_657b34f0`; the 32-bit part looks like a heap address), from the Ethernet receive kproc, `pc` in the low text (`0x80284`, a copy/fill routine). Symbols from an ELF of the same source. The board rebooted itself and came back; nothing Bluetooth-related was running at the time beyond an idle `bt9p`. Third kernel-level failure today (#622 has the other two); this one is the Ethernet data path, not the Dis scheduler.

**Comment by pdfinn** [comment]
Second occurrence, 2026-09-15 13:14:49 local, kernel 2174637: the same abort byte for byte -- `far 0x00000028657b8568`, `elr 0x80284`, `etherrxproc+0x1b8` via `linkproc`, `pid 41 ether0rx` -- with new evidence in the hour before it:

```
12:07:37  ep4.1 channel won't halt hcchar 01188a00
12:56:58  ep4.1 channel won't halt hcchar c1188a00
13:14:49  panic: unhandled exception  (data abort, write, same EL) ... pid 41 ether0rx
```

`ep4.1` is the LAN78xx's bulk-out endpoint; the host controller twice failed to halt its channel. The FAR's low 32 bits again look like a heap address with garbage above -- a 64-bit store through a pointer built from a 32-bit value. Load at the time: an LE mouse streaming reports over Bluetooth (UART, not USB), a network console session, nothing on the Ethernet beyond that session. Board reset itself and came back.

**Comment by pdfinn** [comment]
Status after the #633 receive-path work (commits a5ab27cd1, d953155ec, d19f75642).

Two latent faults turned up in exactly the path this panic lives in, the `ether0rx` kproc's `kchanio` into usbdwc: an unlocked cross-core read-modify-write of `haintmsk`, and a missing cache invalidate after receive DMA that delivered stale bytes as frame data. Both are fixed. Neither by itself explains the signature here (`setlabel+4` with a corrupt `up->nerrlab`): the stale cache corrupted packet payloads, not the Proc. So this is not claimed as the fix.

What stands: no recurrence since the #622 scheduler fix (5 `ether0rx` deaths in the 4 days before it, none since), and the receive path now runs at 164 Mbit/s rather than 7–32, which is a far harder exercise of the same code. The Type-ref and error-stack detectors stay in the kernel, and the 48-hour soak restarts on this kernel (bm74). Any recurrence will be reported here with the detector output.

**Comment by pdfinn** [comment]
Resolved by the receive-path work under #633 (a5ab27cd1, d953155ec, d19f75642) and the scheduler fix under #622: inbound now measures 164-169 Mbit/s at 1400 MHz (223 out), and there has been no ether0rx death since. The Type-ref and error-stack detectors stay in the kernel.
